
on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v2
    - name: run the action
      uses: ./
      with:
        myInput: "Tom peters"
      
    - name: output
      run: |
       echo ${{ steps.hello.outputs.memory }}
       echo " total memory successfully oputput"
     
        
